import Provider from "@/components/Provider";
import "./globals.css";
import Navbar from "../components/Navbar";
import Righbar from "@/components/Righbar";

export const metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className="max-w-[1225px] mx-auto min-h-screen">
          <div className="lg:grid grid-cols-4 ">
            <Navbar />
            <main className="col-span-2">{children}</main>
            <Righbar />
          </div>
        </body>
      </Provider>
    </html>
  );
}
