import Provider from "@/components/Provider";
import "./globals.css";
import Navbar from "../components/Navbar";
import Righbar from "@/components/Righbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className="max-w-[1225px] mx-auto min-h-screen">
          <div className="grid grid-cols-4 ">
            <Navbar />
            <main className="col-span-2">{children}</main>
            <Righbar />
          </div>
        </body>
      </Provider>
    </html>
  );
}
